lib/games/fill_in_the_blanks.dart

UI completed. Animation and game functionality pending.

User Interface completed

---

lib/games/match_the_following.dart

Removed Unwanted comments and UI is done

Satish maui

---

lib/games/match_the_following.dart

Latest Edited Code

---

lib/components/dragbox.dart
lib/components/draggable_text.dart
lib/components/drop_target.dart
lib/games/fill_in_the_blanks.dart

Completed User Interaction. Some Functionality Remains like the wrong letter should return to original value.

Modified Drag and Drop Code

---

lib/games/memory.dart

Memory Matching Multiple Touch Disabled

---

test_driver/calculate_number_test.dart
test_driver/common_function_test.dart

common scrolling function is added for scrolling also in common_function.dart

changes done in common_function

---

lib/games/fill_in_the_blanks.dart

Shuffle is working ,
wrong drag animation working
shaking is working

Finishing the game functionality

---

lib/games/tap_wrong.dart

Deepak maui

---

test_driver/order_it_test.dart

order it test script

---

test_driver/abacus_test.dart

Abacus test scripts

---

lib/games/ClueGame.dart
lib/games/fill_in_the_blanks.dart
lib/games/single_game.dart
lib/screens/game_list_view.dart

added ClueGame and make changes in fill in the blanks

Added ClueGame

---

test_driver/casino.dart
test_driver/casino_test.dart

New casino test files and request to delete the older files(casin.dart and casin_test.dart) as they were renamed to reflect the recommended naming conventions.

Updated Casino test files

---

lib/games/calculate_numbers.dart
lib/games/single_game.dart

Calculate numbers-Resolved the bug

Sudha maui

---

lib/games/Quiz.dart

Resolved layout issues in h-h mode and resolved animation issues for answer buttons

---

lib/games/match_the_following.dart

Codes Updated

---

lib/screens/score_screen.dart

I added two animations one for character and other for the three lower buttons . One bug got resolved related to H_to_H timed mode(navigation back feature on score screen).

Animations Added and one Bug resolved

---

lib/components/flash_card.dart
lib/games/fill_in_the_blanks.dart

Sticking Problem Solved
Flash Card Image is coming
FeedBack size issue solved

Bug resolved for Fill in the blanks

---

lib/games/tap_wrong.dart

Rajesh-chimple TapWrong Game Code Updated

---

lib/games/order_it.dart

Extra Score Getting Added after game end in OrderIt  Isuue Resolved

Fixes #621 OrderIt Score Issue Resolved

---

lib/db/dao/activity_dao.dart
lib/db/entity/activity.dart
lib/repos/activity_repo.dart

Fixes #646 

---

lib/db/dao/quiz_progress_dao.dart
lib/repos/quiz_progress_repo.dart
test/sequence_quiz_test.dart

Sequence Game Widget test files added and deleted functions in QuizProgressDao File added

---

lib/components/camera.dart
lib/screens/login_screen.dart
lib/screens/profile_view.dart
pubspec.yaml

Image Compression and,  camera class is modified.

Image Compression is done.

---

lib/jamaica/widgets/show_rewards.dart

SS-439 Fixed

---

lib/jamaica/widgets/intermediate_quiz_score.dart

intermediate_quiz_score.dart  students are displayed in descending of their score
